apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: "manohardeepu/broker:1.0.2"        
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "30Mi"
            cpu:  "250m"
          limits:
            memory: "128Mi"
            cpu:  "500m"          

---
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      name: main-port
      port: 8080
      targetPort: 8080
