apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: manohardeepu/frontend:1.0.1
        env:
          - name: BROKER_URL
            value: "http://broker.local/"
        ports:
          - containerPort: 8001
        resources:
          requests:
            memory: "30Mi"
            cpu:  "250m"
          limits:
            memory: "128Mi"
            cpu:  "500m"          

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      name: main-port
      port: 8001
      targetPort: 8081