apiVersion: apps/v1
kind: Deployment
metadata:
  name: log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log
  template:
    metadata:
      labels:
        app: log
    spec:
      containers:
      - name: log
        image: manohardeepu/log:1.0.1        
        ports:
          - containerPort: 80
            name: web-port
          - containerPort: 5001
            name: rpc-port
          - containerPort: 50001
            name: grpc-port
        resources:
          requests:
            memory: "30Mi"
            cpu:  "250m"
          limits:
            memory: "128Mi"
            cpu:  "500m"          

---
apiVersion: v1
kind: Service
metadata:
  name: log
spec:
  selector:
    app: log
  ports:
    - protocol: TCP
      name: web-port
      port: 80
      targetPort: 80
    - protocol: TCP
      name: rcp-port
      port: 5001
      targetPort: 5001 
    - protocol: TCP
      name: grpc-port
      port: 50001
      targetPort: 50001             
