apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: "mailhog/mailhog:latest"
        env:
          - name: MAIL_DOMAIN
            value: localhost
          - name: MAIL_HOST
            value: mailhog
          - name: MAIL_PORT
            value: "1025"
          - name: MAIL_ENCRYPTION
            value: "none"
          - name: MAIL_USERNAME
            value: ""
          - name: MAIL_PASSWORD
            value: ""
          - name: MAIL_FROM_NAME
            value: "Mithrandir Gandlf"
          - name: MAIL_FROM_ADDRESS
            value: "mithrandir@middle_earth.com"                                                            
        ports:
          - containerPort: 1025
            name: smtp-port
          - containerPort: 8025
            name: web-port
        resources:
          requests:
            memory: "64Mi"
            cpu:  "250m"
          limits:
            memory: "128Mi"
            cpu:  "500m"          

---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  selector:
    app: mailhog
  ports:
    - protocol: TCP
      name: smtp-port
      port: 1025
      targetPort: 1025
    - protocol: TCP
      name: web-port
      port: 8025
      targetPort: 8025      