apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: "rabbitmq:3.12.10-management-alpine"     
        ports:
          - containerPort: 5672
            name: main-port
          - containerPort: 15671
            name: mgmt-port-1
          - containerPort: 15672
            name: mgmt-port-2
        resources:
          requests:
            memory: "128Mi"
            cpu:  "500m"
          limits:
            memory: "512Mi"
            cpu:  "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      name: main-port
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: mgmt-port-1
      port: 15671
      targetPort: 15671
    - protocol: TCP
      name: mgmt-port-2
      port: 15672
      targetPort: 15672
  type: LoadBalancer