version: "3"
services:
  caddy:
    image: manohardeepu/micro-caddy:1.0.1
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
  frontend:
    image: manohardeepu/frontend:1.0.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BROKER_URL: http://backend/

  broker:
    image: manohardeepu/broker:1.0.1
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    image: manohardeepu/listener-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    image: manohardeepu/authentication-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  log:
    image: manohardeepu/log:1.0.1
    deploy:
      mode: replicated
      replicas: 1

  mail-service:
    image: manohardeepu/mail-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_FROM_NAME: "Gandalf Mithrandir"
      MAIL_FROM_ADDRESS: "shire@middle_earth.com"

  # Mailhog
  mailhog:
    image: "mailhog/mailhog:latest"
    deploy:
      mode: global
    ports:
      - "1025:1025"
      - "8025:8025"
  rabbitmq:
    image: rabbitmq:3.12.10-management-alpine
    ports:
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    deploy:
      mode: global

  # Mongo
  mongo:
    image: "mongo:4.2.16-bionic"
    ports:
      - "27017:27017"
    deploy:
      mode: global
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  #Postgres
  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data/

volumes:
  caddy_data:
    external: true
  caddy_config: